# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 16:15
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BilledProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.FloatField()),
                ('category', models.IntegerField(choices=[(5, 5), (12, 12), (18, 18), (28, 28)])),
                ('hsn', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField(default=datetime.datetime(2017, 9, 19, 16, 15, 15, 864996, tzinfo=utc))),
                ('to', models.CharField(max_length=100)),
                ('collection', models.CharField(choices=[(b'1', b'(CGST/SGST)'), (b'2', b'(IGST)')], default=1, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('inventory', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('hsn_code', models.CharField(blank=True, max_length=8)),
                ('tax', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='billedproducts',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Bills'),
        ),
    ]
