# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 19:42
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170920_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('source', models.CharField(max_length=100)),
                ('cprice', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('on', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterField(
            model_name='bills',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2017, 9, 23, 19, 42, 21, 754461, tzinfo=utc)),
        ),
    ]
