# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-15 04:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170613_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='bills',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2017, 6, 15, 4, 51, 33, 271980, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bills',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2017, 6, 15, 4, 51, 33, 271921, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
