# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 18:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170615_0451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='bills',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2017, 6, 18, 18, 33, 1, 327480, tzinfo=utc)),
        ),
    ]
