# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 18:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170618_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2017, 6, 18, 18, 51, 29, 812428, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tax',
            name='tax',
            field=models.FloatField(default=0),
        ),
    ]
