# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 10:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170618_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='billedproducts',
            name='category',
            field=models.IntegerField(choices=[(5, 5), (12, 12), (18, 18), (28, 28)], default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bills',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 23, 10, 54, 39, 572554, tzinfo=utc)),
        ),
    ]
