# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 11:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170823_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='collection',
            field=models.CharField(choices=[(1, 'Intra State (CGST/SGST)'), (2, 'Inter State (IGST)')], default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='bills',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 23, 11, 39, 35, 749487, tzinfo=utc)),
        ),
    ]
