# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-23 18:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20170823_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='collection',
            field=models.CharField(choices=[(b'1', b'(CGST/SGST)'), (b'2', b'(IGST)')], default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='bills',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 23, 18, 52, 39, 513346, tzinfo=utc)),
        ),
    ]
