# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 18:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20170914_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2017, 9, 14, 18, 13, 39, 605451, tzinfo=utc)),
        ),
    ]
