# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 08:21
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20170915_0630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgroup',
            name='products',
        ),
        migrations.AlterField(
            model_name='bills',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2017, 9, 16, 8, 21, 32, 520529, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.DeleteModel(
            name='ProductGroup',
        ),
    ]
