# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 13:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20170916_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2017, 9, 16, 13, 29, 4, 724922, tzinfo=utc)),
        ),
    ]
